modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/ZareMate/discord-link/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="ZareMate"
description='''Minecraft to Discord account linking with an embedded Discord bot.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.discordlink]]
modId="luckperms"
type="optional"
versionRange="[5.4,6.0)"
ordering="AFTER"
side="SERVER"

[[dependencies.discordlink]]
modId="admin_notes"
type="optional"
versionRange="[1,)"
ordering="AFTER"
side="SERVER"
